export declare const antSelectSelector: string
export declare const buttons: string
export declare const cards: string
export declare const checkboxes: string
export declare const container: string
export declare const dropdowns: string
export declare const inputs: string
export declare const languageSelect: string
export declare const loader: string
export declare const notFound: string
export declare const results: string
export declare const searchBox: string
export declare const spin: string
